### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/minji-o-j#9]
Traceback (most recent call last):
  File "select_dataset.py", line 4, in <module>
    data = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 5

**Comment by minji-o-j** [comment]
python3으로 실행하니

Traceback (most recent call last):
  File "select_dataset.py", line 4, in <module>
    data = pickle.load(f)
ValueError: unsupported pickle protocol: 5

로바뀜

**Comment by minji-o-j** [comment]
docker 설정 해결
